/* SPDX-License-Identifier: MIT */
#ifndef STEM_NPU_VITIS_PLATFORM_H
#define STEM_NPU_VITIS_PLATFORM_H

/*
 * Small Zynq standalone (Vitis) adapter for the portable NPU CSR driver.
 *
 * The PS HP0 port used by the NPU is non-coherent.  A task must therefore
 * live in a cache-line-aligned DDR buffer, be cleaned before the doorbell,
 * and be invalidated before the A9 examines results.  npu_driver.c owns the
 * clean/invalidate ordering; this file provides the Xilinx BSP callbacks.
 */

#include <stddef.h>
#include <stdint.h>

#include "npu_driver.h"

#ifdef __cplusplus
extern "C" {
#endif

#define NPU_VITIS_DEFAULT_TASK_BUFFER_BYTES (2u * 1024u * 1024u)

typedef struct {
    void *cpu_address;
    uint64_t dma_address;
    size_t capacity_bytes;
    size_t staged_bytes;
} npu_vitis_task_buffer_t;

/* Return callbacks backed by Xil_DCacheFlushRange/InvalidateRange and DMB. */
npu_platform_ops_t npu_vitis_platform_ops(void);

/* Initialise a device at an explicit CSR base.  This makes the adapter easy
 * to unit-test and lets applications use the base generated by their XSA. */
npu_result_t npu_vitis_device_init_at(npu_device_t *device,
                                      uintptr_t csr_base);

/* Construct an identity-mapped standalone DDR buffer.  Zynq standalone has
 * no translation between the A9 pointer and the HP0 DMA address. */
npu_result_t npu_vitis_task_buffer_init(npu_vitis_task_buffer_t *buffer,
                                        void *cpu_address,
                                        size_t capacity_bytes);

/* Copy a complete task image into the DMA buffer.  Submission performs the
 * cache clean after this copy, so callers must use npu_vitis_submit_staged(). */
npu_result_t npu_vitis_stage_task(npu_vitis_task_buffer_t *buffer,
                                  const void *task_image,
                                  size_t task_bytes);

npu_result_t npu_vitis_submit_staged(npu_device_t *device,
                                     npu_vitis_task_buffer_t *buffer,
                                     uint32_t task_tag,
                                     uint32_t watchdog_cycles);

/* This is called only after npu_wait() has completed: its cache invalidate
 * covers the entire staged task image, including output tensors. */
int npu_vitis_verify_output(const npu_vitis_task_buffer_t *buffer,
                            size_t output_offset,
                            const void *expected_output,
                            size_t output_bytes);

#ifdef __cplusplus
}
#endif

#endif /* STEM_NPU_VITIS_PLATFORM_H */
