// Generated by scripts/29_generate_npu_isa_headers.py; do not edit.
// P3 draft interface: binary-compatible changes are not yet frozen.
`timescale 1ns/1ps
package npu_isa_pkg;

  localparam int unsigned NPU_ISA_MAJOR = 1;
  localparam int unsigned NPU_ISA_MINOR = 0;
  localparam logic [15:0] NPU_NONE_INDEX = 16'hffff;
  localparam int unsigned NPU_COMMAND_BYTES = 16;
  localparam int unsigned NPU_TENSOR_DESC_BYTES = 64;
  localparam int unsigned NPU_OPERATOR_DESC_BYTES = 64;
  localparam int unsigned NPU_QUANT_DESC_BYTES = 32;
  localparam int unsigned NPU_QUANT_PARAM_BYTES = 16;
  localparam int unsigned NPU_SEGMENT_DESC_BYTES = 8;

  typedef enum logic [7:0] {
    NPU_OP_NOP = 8'h00,
    NPU_OP_WAIT = 8'h01,
    NPU_OP_SIGNAL = 8'h02,
    NPU_OP_END = 8'h03,
    NPU_OP_DMA_LOAD = 8'h10,
    NPU_OP_DMA_STORE = 8'h11,
    NPU_OP_DMA_COPY2D = 8'h12,
    NPU_OP_CONV2D = 8'h20,
    NPU_OP_VEC_ADD = 8'h30,
    NPU_OP_VEC_SUB = 8'h31,
    NPU_OP_VEC_MUL = 8'h32,
    NPU_OP_VEC_MINMAX = 8'h33,
    NPU_OP_ACT = 8'h40,
    NPU_OP_REQUANT = 8'h41,
    NPU_OP_UPSAMPLE2X = 8'h42,
    NPU_OP_POOL2D = 8'h43,
    NPU_OP_COPY_LAYOUT = 8'h44
  } npu_opcode_e;

  localparam logic [7:0] NPU_FLAG_ASYNC = 8'h01;
  localparam logic [7:0] NPU_FLAG_IRQ = 8'h02;
  localparam logic [7:0] NPU_FLAG_SATURATE = 8'h04;
  localparam logic [7:0] NPU_FLAG_FUSED_POST_OP = 8'h08;

  typedef enum logic [7:0] {
    NPU_DTYPE_INT8 = 8'h01,
    NPU_DTYPE_INT12_IN_INT16 = 8'h02,
    NPU_DTYPE_INT16 = 8'h03,
    NPU_DTYPE_INT32 = 8'h04,
    NPU_DTYPE_UINT8 = 8'h05
  } npu_dtype_e;

  typedef enum logic [7:0] {
    NPU_LAYOUT_LINEAR = 8'h00,
    NPU_LAYOUT_NHWC8 = 8'h01,
    NPU_LAYOUT_WEIGHT_O8I8 = 8'h02,
    NPU_LAYOUT_SEGMENTED = 8'h03
  } npu_layout_e;

  typedef enum logic [15:0] {
    NPU_POST_NONE = 16'h0000,
    NPU_POST_RELU = 16'h0001,
    NPU_POST_LEAKY_RELU_0P1 = 16'h0002,
    NPU_POST_TANH_LUT = 16'h0003
  } npu_post_op_e;

  localparam logic [7:0] NPU_EVENT_A0_READY = 8'h01;
  localparam logic [7:0] NPU_EVENT_A1_READY = 8'h02;
  localparam logic [7:0] NPU_EVENT_W0_READY = 8'h04;
  localparam logic [7:0] NPU_EVENT_W1_READY = 8'h08;
  localparam logic [7:0] NPU_EVENT_C0_DONE = 8'h10;
  localparam logic [7:0] NPU_EVENT_C1_DONE = 8'h20;
  localparam logic [7:0] NPU_EVENT_S0_DONE = 8'h40;
  localparam logic [7:0] NPU_EVENT_S1_DONE = 8'h80;

  typedef enum logic [15:0] {
    NPU_ERR_NONE = 16'h0000,
    NPU_ERR_ILLEGAL_OPCODE = 16'h0001,
    NPU_ERR_ILLEGAL_FLAGS = 16'h0002,
    NPU_ERR_ILLEGAL_FIELDS = 16'h0003,
    NPU_ERR_EXECUTION_ERROR = 16'h0004,
    NPU_ERR_WATCHDOG = 16'h0005
  } npu_error_code_e;

  localparam int unsigned NPU_IMM_EVENT_LSB = 0;
  localparam int unsigned NPU_IMM_EVENT_WIDTH = 8;
  localparam int unsigned NPU_IMM_ACTIVATION_BANK_BIT = 8;
  localparam int unsigned NPU_IMM_WEIGHT_BANK_BIT = 9;
  localparam int unsigned NPU_IMM_ACCUMULATOR_BANK_BIT = 10;
  localparam int unsigned NPU_IMM_OUTPUT_BANK_BIT = 11;
  localparam int unsigned NPU_IMM_SEGMENT_LSB = 12;
  localparam int unsigned NPU_IMM_SEGMENT_WIDTH = 2;
  localparam int unsigned NPU_IMM_SEGMENTED_BIT = 14;

  // Declarations run from MSB to LSB; opcode therefore occupies bits 7:0.
  typedef struct packed {
    logic [15:0] imm;
    logic [15:0] quant_desc;
    logic [15:0] op_desc;
    logic [15:0] src1_td;
    logic [15:0] src0_td;
    logic [15:0] dst_td;
    logic [15:0] tag;
    logic [7:0]  flags;
    logic [7:0]  opcode;
  } npu_command_t;

  typedef struct packed {
    logic [127:0] reserved;
    logic [31:0]  segment_offset;
    logic [15:0]  flags;
    logic [15:0]  segment_count;
    logic [15:0]  quant_desc;
    logic [7:0]   layout;
    logic [7:0]   dtype;
    logic [31:0]  stride_c;
    logic [31:0]  stride_w;
    logic [31:0]  stride_h;
    logic [31:0]  stride_n;
    logic [15:0]  shape_c;
    logic [15:0]  shape_w;
    logic [15:0]  shape_h;
    logic [15:0]  shape_n;
    logic [31:0]  allocation_bytes;
    logic [63:0]  base_offset;
  } npu_tensor_desc_t;

  typedef struct packed {
    logic [31:0] input_channel_count;
    logic [31:0] input_channel_start;
    logic [31:0] tile_cout;
    logic [31:0] tile_w;
    logic [31:0] tile_h;
    logic [31:0] tile_origin_cout;
    logic [31:0] tile_origin_w;
    logic [31:0] tile_origin_h;
    logic [15:0] post_op_id;
    logic [15:0] groups;
    logic [15:0] pad_right;
    logic [15:0] pad_left;
    logic [15:0] pad_bottom;
    logic [15:0] pad_top;
    logic [15:0] dilation_w;
    logic [15:0] dilation_h;
    logic [15:0] stride_w;
    logic [15:0] stride_h;
    logic [15:0] kw;
    logic [15:0] kh;
    logic [15:0] bias_td;
    logic [15:0] weight_td;
    logic [15:0] dst_td;
    logic [15:0] src_td;
  } npu_operator_desc_t;

  typedef struct packed {
    logic [95:0]        reserved1;
    logic [15:0]        reserved0;
    logic [15:0]        post_op_id;
    logic signed [31:0] clamp_max;
    logic signed [31:0] clamp_min;
    logic [31:0]        param_count;
    logic [31:0]        param_offset;
  } npu_quant_desc_t;

  typedef struct packed {
    logic signed [31:0] clamp_max;
    logic signed [31:0] clamp_min;
    logic [23:0]        reserved;
    logic [7:0]         shift;
    logic signed [31:0] multiplier;
  } npu_quant_param_t;

  typedef struct packed {
    logic [15:0] reserved;
    logic [15:0] channel_count;
    logic [15:0] dst_channel;
    logic [15:0] tensor_index;
  } npu_segment_desc_t;

  function automatic logic [7:0] npu_imm_event_mask(input logic [15:0] imm);
    npu_imm_event_mask = imm[7:0];
  endfunction

endpackage : npu_isa_pkg
