/* Generated by scripts/29_generate_npu_isa_headers.py; do not edit. */
/* P3 draft interface. The host and task image are little-endian. */
#ifndef STEM_NPU_ISA_H
#define STEM_NPU_ISA_H

#include <stddef.h>
#include <stdint.h>

#define NPU_ISA_MAJOR 1u
#define NPU_ISA_MINOR 0u
#define NPU_NONE_INDEX 0xffffu
#define NPU_COMMAND_BYTES 16u
#define NPU_TENSOR_DESC_BYTES 64u
#define NPU_OPERATOR_DESC_BYTES 64u
#define NPU_QUANT_DESC_BYTES 32u
#define NPU_QUANT_PARAM_BYTES 16u
#define NPU_SEGMENT_DESC_BYTES 8u

#define NPU_OP_NOP 0x00u
#define NPU_OP_WAIT 0x01u
#define NPU_OP_SIGNAL 0x02u
#define NPU_OP_END 0x03u
#define NPU_OP_DMA_LOAD 0x10u
#define NPU_OP_DMA_STORE 0x11u
#define NPU_OP_DMA_COPY2D 0x12u
#define NPU_OP_CONV2D 0x20u
#define NPU_OP_VEC_ADD 0x30u
#define NPU_OP_VEC_SUB 0x31u
#define NPU_OP_VEC_MUL 0x32u
#define NPU_OP_VEC_MINMAX 0x33u
#define NPU_OP_ACT 0x40u
#define NPU_OP_REQUANT 0x41u
#define NPU_OP_UPSAMPLE2X 0x42u
#define NPU_OP_POOL2D 0x43u
#define NPU_OP_COPY_LAYOUT 0x44u

#define NPU_FLAG_ASYNC 0x01u
#define NPU_FLAG_IRQ 0x02u
#define NPU_FLAG_SATURATE 0x04u
#define NPU_FLAG_FUSED_POST_OP 0x08u

#define NPU_DTYPE_INT8 0x01u
#define NPU_DTYPE_INT12_IN_INT16 0x02u
#define NPU_DTYPE_INT16 0x03u
#define NPU_DTYPE_INT32 0x04u
#define NPU_DTYPE_UINT8 0x05u

#define NPU_LAYOUT_LINEAR 0x00u
#define NPU_LAYOUT_NHWC8 0x01u
#define NPU_LAYOUT_WEIGHT_O8I8 0x02u
#define NPU_LAYOUT_SEGMENTED 0x03u

#define NPU_POST_NONE 0x00u
#define NPU_POST_RELU 0x01u
#define NPU_POST_LEAKY_RELU_0P1 0x02u
#define NPU_POST_TANH_LUT 0x03u

#define NPU_EVENT_A0_READY 0x01u
#define NPU_EVENT_A1_READY 0x02u
#define NPU_EVENT_W0_READY 0x04u
#define NPU_EVENT_W1_READY 0x08u
#define NPU_EVENT_C0_DONE 0x10u
#define NPU_EVENT_C1_DONE 0x20u
#define NPU_EVENT_S0_DONE 0x40u
#define NPU_EVENT_S1_DONE 0x80u

#define NPU_IMM_EVENT_LSB 0u
#define NPU_IMM_EVENT_WIDTH 8u
#define NPU_IMM_EVENT_MASK 0x00ffu
#define NPU_IMM_ACTIVATION_BANK_BIT 8u
#define NPU_IMM_WEIGHT_BANK_BIT 9u
#define NPU_IMM_ACCUMULATOR_BANK_BIT 10u
#define NPU_IMM_OUTPUT_BANK_BIT 11u
#define NPU_IMM_SEGMENT_LSB 12u
#define NPU_IMM_SEGMENT_WIDTH 2u
#define NPU_IMM_SEGMENTED_BIT 14u

#pragma pack(push, 1)
typedef struct {
    uint8_t opcode;
    uint8_t flags;
    uint16_t tag;
    uint16_t dst_td;
    uint16_t src0_td;
    uint16_t src1_td;
    uint16_t op_desc;
    uint16_t quant_desc;
    uint16_t imm;
} npu_command_t;

typedef struct {
    uint64_t base_offset;
    uint32_t allocation_bytes;
    uint16_t shape_n, shape_h, shape_w, shape_c;
    uint32_t stride_n, stride_h, stride_w, stride_c;
    uint8_t dtype;
    uint8_t layout;
    uint16_t quant_desc;
    uint16_t segment_count;
    uint16_t flags;
    uint32_t segment_offset;
    uint8_t reserved[16];
} npu_tensor_desc_t;

typedef struct {
    uint16_t src_td, dst_td, weight_td, bias_td;
    uint16_t kh, kw, stride_h, stride_w;
    uint16_t dilation_h, dilation_w;
    uint16_t pad_top, pad_bottom, pad_left, pad_right;
    uint16_t groups, post_op_id;
    uint32_t tile_origin_h, tile_origin_w, tile_origin_cout;
    uint32_t tile_h, tile_w, tile_cout;
    uint32_t input_channel_start, input_channel_count;
} npu_operator_desc_t;

typedef struct {
    uint32_t param_offset, param_count;
    int32_t clamp_min, clamp_max;
    uint16_t post_op_id, reserved0;
    uint8_t reserved1[12];
} npu_quant_desc_t;

typedef struct {
    int32_t multiplier;
    uint8_t shift;
    uint8_t reserved[3];
    int32_t clamp_min, clamp_max;
} npu_quant_param_t;

typedef struct {
    uint16_t tensor_index, dst_channel, channel_count, reserved;
} npu_segment_desc_t;
#pragma pack(pop)

#if defined(__cplusplus)
#define NPU_STATIC_ASSERT(c, m) static_assert((c), m)
#else
#define NPU_STATIC_ASSERT(c, m) _Static_assert((c), m)
#endif
NPU_STATIC_ASSERT(sizeof(npu_command_t) == NPU_COMMAND_BYTES, "command size");
NPU_STATIC_ASSERT(sizeof(npu_tensor_desc_t) == NPU_TENSOR_DESC_BYTES, "tensor size");
NPU_STATIC_ASSERT(sizeof(npu_operator_desc_t) == NPU_OPERATOR_DESC_BYTES, "operator size");
NPU_STATIC_ASSERT(sizeof(npu_quant_desc_t) == NPU_QUANT_DESC_BYTES, "quant desc size");
NPU_STATIC_ASSERT(sizeof(npu_quant_param_t) == NPU_QUANT_PARAM_BYTES, "quant param size");
NPU_STATIC_ASSERT(sizeof(npu_segment_desc_t) == NPU_SEGMENT_DESC_BYTES, "segment size");
NPU_STATIC_ASSERT(offsetof(npu_command_t, opcode) == 0, "command opcode offset");
NPU_STATIC_ASSERT(offsetof(npu_command_t, tag) == 2, "command tag offset");
NPU_STATIC_ASSERT(offsetof(npu_command_t, dst_td) == 4, "command dst offset");
NPU_STATIC_ASSERT(offsetof(npu_command_t, src0_td) == 6, "command src0 offset");
NPU_STATIC_ASSERT(offsetof(npu_command_t, src1_td) == 8, "command src1 offset");
NPU_STATIC_ASSERT(offsetof(npu_command_t, op_desc) == 10, "command operator offset");
NPU_STATIC_ASSERT(offsetof(npu_command_t, quant_desc) == 12, "command quant offset");
NPU_STATIC_ASSERT(offsetof(npu_command_t, imm) == 14, "command immediate offset");
NPU_STATIC_ASSERT(offsetof(npu_tensor_desc_t, base_offset) == 0, "tensor base offset");
NPU_STATIC_ASSERT(offsetof(npu_tensor_desc_t, shape_n) == 12, "tensor shape offset");
NPU_STATIC_ASSERT(offsetof(npu_tensor_desc_t, stride_n) == 20, "tensor stride offset");
NPU_STATIC_ASSERT(offsetof(npu_tensor_desc_t, dtype) == 36, "tensor dtype offset");
NPU_STATIC_ASSERT(offsetof(npu_tensor_desc_t, segment_offset) == 44, "tensor segment offset");
NPU_STATIC_ASSERT(offsetof(npu_operator_desc_t, src_td) == 0, "operator src offset");
NPU_STATIC_ASSERT(offsetof(npu_operator_desc_t, post_op_id) == 30, "operator post offset");
NPU_STATIC_ASSERT(offsetof(npu_operator_desc_t, tile_origin_h) == 32, "operator tile offset");
NPU_STATIC_ASSERT(offsetof(npu_operator_desc_t, input_channel_count) == 60, "operator input count offset");
NPU_STATIC_ASSERT(offsetof(npu_quant_desc_t, clamp_min) == 8, "quant clamp offset");
NPU_STATIC_ASSERT(offsetof(npu_quant_desc_t, post_op_id) == 16, "quant post offset");
NPU_STATIC_ASSERT(offsetof(npu_quant_param_t, shift) == 4, "quant shift offset");
NPU_STATIC_ASSERT(offsetof(npu_quant_param_t, clamp_min) == 8, "quant param clamp offset");
NPU_STATIC_ASSERT(offsetof(npu_segment_desc_t, channel_count) == 4, "segment count offset");
#undef NPU_STATIC_ASSERT

static inline uint16_t npu_imm_encode(uint8_t event_mask,
                                      uint8_t activation_bank,
                                      uint8_t weight_bank,
                                      uint8_t accumulator_bank,
                                      uint8_t output_bank,
                                      uint8_t segmented,
                                      uint8_t segment_index) {
    return (uint16_t)(event_mask
        | ((activation_bank & 1u) << NPU_IMM_ACTIVATION_BANK_BIT)
        | ((weight_bank & 1u) << NPU_IMM_WEIGHT_BANK_BIT)
        | ((accumulator_bank & 1u) << NPU_IMM_ACCUMULATOR_BANK_BIT)
        | ((output_bank & 1u) << NPU_IMM_OUTPUT_BANK_BIT)
        | ((segment_index & 3u) << NPU_IMM_SEGMENT_LSB)
        | ((segmented & 1u) << NPU_IMM_SEGMENTED_BIT));
}

#endif /* STEM_NPU_ISA_H */
