hardware/rtl/include/npu_isa_pkg.sv
hardware/rtl/include/npu_dma_pkg.sv
hardware/rtl/npu_command_processor.sv
hardware/rtl/npu_descriptor_cache.sv
hardware/rtl/npu_u32_mul_iter.sv
hardware/rtl/npu_dma_agu.sv
hardware/rtl/npu_dma_frontend.sv
hardware/rtl/npu_dma_engine.sv
hardware/rtl/npu_scratchpad_bank.sv
hardware/rtl/npu_scratchpad.sv
hardware/rtl/npu_dma_subsystem.sv
hardware/rtl/npu_tensor_mac_8x8.sv
