#!/usr/bin/env python3
"""Generate ignored Vitis C payload sources from one NPU task and golden output."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


TASK_ALIGNMENT = 64
TASK_HEADER_BYTES = 256


def c_array(name: str, payload: bytes) -> str:
    rows = []
    for offset in range(0, len(payload), 12):
        values = ", ".join(f"0x{value:02x}" for value in payload[offset:offset + 12])
        rows.append(f"    {values},")
    return "\n".join((f"const uint8_t {name}[{len(payload)}] = {{", *rows, "};"))


def derive_metadata(program_dir: Path, golden_bytes: int) -> tuple[int, int]:
    program = json.loads((program_dir / "program.json").read_text(encoding="utf-8"))
    manifest = json.loads((program_dir / "task_image.json").read_text(encoding="utf-8"))
    output_index = int(program["entry"]["output_tensor"])
    tensor = program["tensors"][output_index]
    output_offset = (int(manifest["sections"]["activation"]["offset"])
                     + int(tensor["base_offset"]))
    command_count = int(manifest["command_count"])
    if golden_bytes <= 0:
        raise ValueError("golden output must not be empty")
    return output_offset, command_count


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image", type=Path, required=True)
    parser.add_argument("--golden", type=Path, required=True)
    parser.add_argument("--program-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    args = parser.parse_args()

    image = args.image.read_bytes()
    golden = args.golden.read_bytes()
    if len(image) < TASK_HEADER_BYTES or len(image) % TASK_ALIGNMENT:
        raise ValueError("task image must be at least 256 bytes and 64-byte aligned")
    output_offset, command_count = derive_metadata(args.program_dir, len(golden))
    if output_offset < 0 or output_offset + len(golden) > len(image):
        raise ValueError("derived golden output range lies outside task image")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    header = args.output_dir / "navigator_npu_task_payload.h"
    source = args.output_dir / "navigator_npu_task_payload.c"
    header.write_text(
        "/* Generated by scripts/63_generate_vitis_task_payload.py; do not edit. */\n"
        "#ifndef NAVIGATOR_NPU_TASK_PAYLOAD_H\n"
        "#define NAVIGATOR_NPU_TASK_PAYLOAD_H\n"
        "#include <stddef.h>\n#include <stdint.h>\n"
        "extern const uint8_t navigator_npu_task_image[];\n"
        "extern const size_t navigator_npu_task_image_bytes;\n"
        "extern const uint8_t navigator_npu_expected_output[];\n"
        "extern const size_t navigator_npu_expected_output_bytes;\n"
        "extern const size_t navigator_npu_output_offset;\n"
        "extern const uint32_t navigator_npu_expected_command_count;\n"
        "#endif\n",
        encoding="utf-8",
    )
    source.write_text(
        "/* Generated by scripts/63_generate_vitis_task_payload.py; do not edit. */\n"
        "#include \"navigator_npu_task_payload.h\"\n\n"
        + c_array("navigator_npu_task_image", image) + "\n\n"
        + c_array("navigator_npu_expected_output", golden) + "\n\n"
        f"const size_t navigator_npu_task_image_bytes = {len(image)}u;\n"
        f"const size_t navigator_npu_expected_output_bytes = {len(golden)}u;\n"
        f"const size_t navigator_npu_output_offset = {output_offset}u;\n"
        f"const uint32_t navigator_npu_expected_command_count = {command_count}u;\n",
        encoding="utf-8",
    )
    print(f"VITIS_PAYLOAD image={len(image)} golden={len(golden)} "
          f"output_offset={output_offset} commands={command_count} dir={args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
