#!/usr/bin/env python3
"""Generate deterministic C filterbank constants from the target model source."""
from __future__ import annotations

import argparse
import ast
import hashlib
import math
from pathlib import Path

import numpy as np


ROOT = Path(__file__).resolve().parents[1]
MODEL_SOURCE = ROOT / "scripts" / "09_target_model.py"
COMMON_SOURCE = ROOT / "scripts" / "common.py"
OUTPUT_DEFAULT = ROOT / "software" / "audio_player" / "generated"
FILTERBANK_FUNCTIONS = {
    "band_edges",
    "_mel_points",
    "band_centers",
    "_center_interpolation",
    "make_analysis_matrix",
    "make_synthesis_matrix",
}
FILTERBANK_CONSTANTS = {
    "N_FFT",
    "HOP",
    "N_BINS",
    "N_BANDS",
    "FMIN",
    "FMAX",
    "DEFAULT_BAND_LAYOUT",
}


def load_literal_assignment(path: Path, name: str) -> object:
    tree = ast.parse(path.read_text(encoding="utf-8"), path.name)
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        if any(isinstance(target, ast.Name) and target.id == name
               for target in node.targets):
            return ast.literal_eval(node.value)
    raise RuntimeError(f"literal assignment {name} missing from {path}")


def load_filterbank_namespace() -> dict[str, object]:
    """Execute only the dependency-light filterbank portion of the model file."""
    def assigned_names(target: ast.expr) -> set[str]:
        if isinstance(target, ast.Name):
            return {target.id}
        if isinstance(target, (ast.Tuple, ast.List)):
            return set().union(*(assigned_names(item) for item in target.elts))
        return set()

    tree = ast.parse(MODEL_SOURCE.read_text(encoding="utf-8"), MODEL_SOURCE.name)
    selected: list[ast.stmt] = []
    for node in tree.body:
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            names = set().union(*(assigned_names(target) for target in targets))
            if names & FILTERBANK_CONSTANTS:
                selected.append(node)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.name in FILTERBANK_FUNCTIONS:
                selected.append(node)
    namespace: dict[str, object] = {
        "math": math,
        "np": np,
        "SR": load_literal_assignment(COMMON_SOURCE, "SR"),
    }
    module = ast.fix_missing_locations(ast.Module(body=selected, type_ignores=[]))
    exec(compile(module, str(MODEL_SOURCE), "exec"), namespace)
    missing = (FILTERBANK_FUNCTIONS | FILTERBANK_CONSTANTS) - namespace.keys()
    if missing:
        raise RuntimeError(f"target model filterbank definitions missing: {sorted(missing)}")
    return namespace


def float_rows(values: np.ndarray) -> str:
    def c_float(value: np.float32) -> str:
        literal = f"{float(value):.9g}"
        if "." not in literal and "e" not in literal.lower():
            literal += ".0"
        return literal + "f"

    rows = []
    for row in values:
        tokens = ", ".join(c_float(value) for value in row)
        rows.append(f"    {{{tokens}}},")
    return "\n".join(rows)


def digest_le_f32(values: np.ndarray) -> str:
    return hashlib.sha256(np.asarray(values, dtype="<f4").tobytes(order="C")).hexdigest()


def expected_outputs(output_dir: Path) -> dict[Path, bytes]:
    namespace = load_filterbank_namespace()
    layout = str(namespace["DEFAULT_BAND_LAYOUT"])
    bands = int(namespace["N_BANDS"])
    analysis_fn = namespace["make_analysis_matrix"]
    synthesis_fn = namespace["make_synthesis_matrix"]
    if not callable(analysis_fn) or not callable(synthesis_fn):
        raise TypeError("target model filterbank definitions are not callable")

    analysis = np.asarray(analysis_fn(bands, layout=layout), dtype="<f4")
    synthesis_reference = np.asarray(
        synthesis_fn(bands, layout=layout), dtype="<f4"
    )
    synthesis = np.ascontiguousarray(synthesis_reference.T, dtype="<f4")
    if analysis.shape != (513, 128):
        raise ValueError(f"unexpected analysis shape: {analysis.shape}")
    if synthesis.shape != (128, 513):
        raise ValueError(f"unexpected synthesis shape: {synthesis.shape}")
    dead_bands = int(np.count_nonzero(np.count_nonzero(analysis, axis=0) == 0))
    if layout != "legacy_log" or dead_bands != 49:
        raise ValueError(
            "filterbank no longer matches the deployed legacy_log checkpoint"
        )
    row_sums = synthesis_reference.astype(np.float64).sum(axis=1)
    if not np.allclose(row_sums, 1.0, rtol=0.0, atol=1e-7):
        raise ValueError("synthesis filterbank rows do not sum to one")

    analysis_sha = digest_le_f32(analysis)
    synthesis_sha = digest_le_f32(synthesis)
    header = (
        "/* Generated by scripts/98_generate_stem_constants.py; do not edit. */\n"
        "#ifndef STEM_FILTERBANK_H\n"
        "#define STEM_FILTERBANK_H\n\n"
        "#include \"stem_contract.h\"\n\n"
        "#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n"
        "extern const float stem_analysis[STEM_FFT_BINS][STEM_BAND_COUNT];\n"
        "extern const float stem_synthesis[STEM_BAND_COUNT][STEM_FFT_BINS];\n\n"
        "#ifdef __cplusplus\n}\n#endif\n\n"
        "#endif /* STEM_FILTERBANK_H */\n"
    )
    source = (
        "/* Generated by scripts/98_generate_stem_constants.py; do not edit.\n"
        f" * layout: {layout}; compatibility-dead-bands: {dead_bands}\n"
        f" * analysis-le-f32-sha256: {analysis_sha}\n"
        f" * synthesis-le-f32-sha256: {synthesis_sha}\n"
        " */\n"
        "#include \"stem_filterbank.h\"\n\n"
        "const float stem_analysis[513][128] = {\n"
        f"{float_rows(analysis)}\n"
        "};\n\n"
        "const float stem_synthesis[128][513] = {\n"
        f"{float_rows(synthesis)}\n"
        "};\n"
    )
    return {
        output_dir / "stem_filterbank.h": header.encode("ascii"),
        output_dir / "stem_filterbank.c": source.encode("ascii"),
    }


def write_or_check(outputs: dict[Path, bytes], check: bool) -> None:
    for path, expected in outputs.items():
        if check:
            if not path.is_file() or path.read_bytes() != expected:
                raise SystemExit(f"out of date: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(expected)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=OUTPUT_DEFAULT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    outputs = expected_outputs(args.output_dir.resolve())
    write_or_check(outputs, args.check)
    action = "verified" if args.check else "generated"
    print(f"stem filterbank: {action} {len(outputs)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
